# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161206_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'permissions': (('can_view_account', 'Can view account'),)},
        ),
        migrations.AlterModelOptions(
            name='chargemodel',
            options={'permissions': (('can_view_account', 'Can view account'),)},
        ),
    ]
