# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20161206_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='chargemodel',
            options={},
        ),
    ]
